version: '3'

services:
  prometheus1:
    container_name: prometheus_container1
    image: prom/prometheus
    volumes:
      - ./prometheus1:/etc/prometheus
    ports:
      - 9090:9090
    command: --config.file=/etc/prometheus/prometheus.yml

  prometheus2:
    container_name: prometheus_container2
    image: prom/prometheus
    volumes:
      - ./prometheus2:/etc/prometheus
    ports:
      - 9091:9090
    command: --config.file=/etc/prometheus/prometheus.yml

  prometheus3:
    container_name: prometheus_container3
    image: prom/prometheus
    volumes:
      - ./prometheus3:/etc/prometheus
    ports:
      - 9092:9090
    command: --config.file=/etc/prometheus/prometheus.yml

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    ports:
      - 9093:9093
    command: --config.file=/etc/alertmanager/alertmanager.yml

  node-exporter:
    container_name: node_exporter
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - 9100:9100
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
