global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus1:9090', 'prometheus2:9090', 'prometheus3:9090']

  - job_name: 'node_exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['node_exporter:9100']
  - job_name: 'cadvisor'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cadvisor:8080']
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
rule_files:
  - '/etc/prometheus/rules/*.rules'
